### ISSUE TITLE
Error when first metric is excluded

### ISSUE THREAD

**Issue by aalaran** [GoogleCloudPlatform/stackdriver-metrics-export#4]
An issue was discovered whereby the app fails if the first metric from metricDescriptors is excluded. Furthermore, a side effect is wrong stats are saved if a metric is excluded but the previous one wasn't, given that the scope of the message_to_publish variable is functionally global. In this instance, the information from the previous metric is saved at least twice.

**Comment by charlesbaer** [comment]
Thanks for pointing this out. I have addressed the issue along with the latest updates.
